version: "3.8"

networks:
  boraimpactar:
    external: true

volumes:
  postgres_data:

services:
  database:
    image: postgres:15
    container_name: marketplace_postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: bi_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - boraimpactar

  marketplace_backend:
    build: ./back
    container_name: marketplace_backend
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: docker
      DB_PASS: senha123
      DB_NAME: bi_banco
    ports:
      - "3018:3018"
    networks:
      - boraimpactar

  marketplace_frontend:
    container_name: marketplace_frontend
    build: ./front
    ports:
      - "3008:3008"
    environment:
      - PORT=3008
    networks:
      - boraimpactar
